### PR TITLE
Added Channel endpoints, logic and tests.

### PR DESCRIPTION
**Pull request by nick13jaremek**
Includes improvements to SMS endpoint Cucumber test.

### CODE REVIEW

**Comment by nick13jaremek** [comment]
Please, ignore this pull request for now. There is some inconsistent behaviour when running tests locally and on the CircleCI machine: tests are GREEN on my local machine but a couple of them fail on CircleCI.

Will keep investigating.

**Comment by nick13jaremek** [comment]
@luismesas The issue with the CircleCI tests is finally resolved. I configured the circleci configuration file to install and use a local MongoDB installation. Will contact CircleCI for more details though.

**Comment by luismesas** [comment]
The solution is a bit Salomonic.

If you follow this link https://circleci.com/docs/environment you can see that the mongo version on circle environment is 2.4.12, you are installing on 2.6, can you try to change your local docker mongodb to 2.4 and see if you can reproduce the test failures?

**Comment by nick13jaremek** [comment]
@luismesas Switching to an older MongoDB version breaks the tests again. Version 2.6 is the one I use in my local machine, that is the reason I decided to install version 2.6.3.

**Comment by guumaster** [comment]
I just run the build again with no cache and it has failed. Upgrading the Mongo Version would only hide the error. @nick13jaremek could you try to use a mongodb 2.4 docker service and try to pass the tests width the same setup?

**Comment by luismesas** [comment]
this branch has lost compatibility, @guumaster @nick13jaremek can you take a look at how to make this?

There is a way on CircleCi to run the tests in parallel over different setups, soy maybe we should run it with versions 2.4, 2.6 and maybe 3.0  of MongoDB.

What do you think?

**Comment by nick13jaremek** [comment]
**Issue**: for the DELETE `/api/channel/:channelId/identities/:identityId` endpoint, two Cucumber tests yield a success response when deleting non-existing documents in the Mongo datastore. **These tests should yield an error**. 

**Cause**: MongoDB 2.6 returns a response with a an `nModified` field which is used to determine whether some document has been updated. However, MongoDB 2.4 does *NOT* include this `nModified` field, skipping the error callback in the *Resonator* code and yielding an incorrect success test output in certain cases, instead of the yielding the expected error.

I implemented a waterwall function to look for the Channel and Identity objects involved in the request, check their associations and update them accordingly. If any of the steps fail, then the application returns a HTTP error message to the requester. @luismesas

**Pull request merged**
