### PR TITLE
Feature/push refactor

### PR DESCRIPTION
**Pull request by nick13jaremek**
Refactored push notification platforms to use the Orchestrator as manager, including tests.

### CODE REVIEW

**Comment by guumaster** [comment]
closed until we add dredd testing.

**Comment by luismesas** [comment]
Excluded scripts folder from Coverage. Ey, thats a big cheat!!!

I will be looking deeper on echa pull request from now...

**Comment by guumaster** [comment]
hehe, well, we are not trying to cheat, `scripts` folder are tools and helpers to run the tests, dredd, fixtures and mocks. 

If we cover that with tests it would be the tests of tests, and we'll get into a downward spiral of infinite testing for all eternity :laughing: :laughing:

**Comment by luismesas** [comment]
Any file of code must be cover and here is the explanation:

- If its code, it must be covered because it will be executed at runtime and must to be tested.
- If it's a test, it must be covered because if it is not covered means that the test is no being executed. It must be executed or deleted from the project.
- If it's a helper script, it must be covered because if no test covers it we can freely remove as it is not being used. We don't want any crap on the project. It must be covered or deleted from the project.

Even deploy scripts must be covered, but that is for a different conversation.

So no more exclusions, please

**Comment by guumaster** [comment]
got it, we'll re-add it in next PR.

**Pull request closed without merging**
