### PR TITLE
Feature/normalize errors

### PR DESCRIPTION
**Pull request by nick13jaremek**
Restify-to-Express conversion finished with Mocha and Cucumber tests updated accordingly.
HttpErrors are sent from the Express error handler. 

The platform modules yield standard Error objects when an error occurs, either due to an exception caused by MongoDB or any other third-party module, or due to an error condition specified on our own.

### CODE REVIEW

**Comment by guumaster** [comment]
TL;DR: :-1: 

Why are you removing clear error codes in favor of 500? Errors 500 must be ONLY a last resource, but all the errors replaced in this commits are known to the program. Please, leave `restify-errors` as a dependency and nice error codes. `express` and `restify-errors` can coexist nicely.

**Comment by nick13jaremek** [comment]
@guumaster So you want me to return HttpErrors from `restify-errors` for all the known error programs and routers, but leave the `return callback(err)` for the rest of cases? This would mean we would still return HttpErrors in case anyone used the module skipping the routes, using the platforms only.

**Comment by guumaster** [comment]
Yes, right now I prefer to have responses with clear errors, and leave usage outside of the API for later. As example, if we do this: 

```javascript
// some-platform.js
if (something_wrong) {
    return callback(new Error('something specific went wrong'));
}

// some-router.js
if (err && err.message === 'something specific went wrong') ) {
   return callback(new errors.BadRequest('Something specific went wrong');
}
```
But we are not coding usage outside of the API anytime soon.So for more clarity, you can leave http errors in platforms. 

Leave error 500 for when any unknown error shows up. And when you caught them in the logs, check if it can be avoided with code and not throw a 500 to the user.

**Comment by nick13jaremek** [comment]
@guumaster Okay, then I can do as you show in the code example: the platforms return Error objects in case an error occurs, with a custom message. Then this message is checked at the router as you show, and a HttpError object is returned:

    // some-router.js
    if (err && err.message === 'something specific went wrong') ) {
    return callback(new errors.BadRequest('Something specific went wrong');
    }

This would mean some routers will have lots of if cases for the HttpError checking, depending on the number of involved functions related to the router action.

Another approach would be returning HttpErrors from the platforms and have the router simply do `return callback(err)` in case *err* is not null.

The first approach would be better I guess. What do you think?

**Comment by guumaster** [comment]
> Another approach would be returning HttpErrors from the platforms and have the router simply do return callback(err) in case err is not null.

:+1: reopen PR after those changes.

**Comment by nick13jaremek** [comment]
Will as soon as I can. :+1:

**Pull request closed without merging**
